### ISSUE TITLE
Generating a Server 500 Error when sending email

### ISSUE THREAD

**Issue by bluehiveinteractive** [wp3sixty/woo-custom-emails#36]
When attempting to send an email after selecting it from the Orders Actions dropdown list, the following error is being logged after a Server 500 Error. Reverted to default TwentySeventeen and deactivated all plugins except this one and woocommerce.

`Fatal error: Uncaught Error: Call to a member function get_id() on null in /home/amishyard/public_html/wp-content/plugins/woo-custom-emails/admin/class-wcemails-admin.php:573 Stack trace: #0 /home/amishyard/public_html/wp-includes/class-wp-hook.php(288): WCEmails_Admin->do_email_actions(167611, Object(WP_Post)) #1 /home/amishyard/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /home/amishyard/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/amishyard/public_html/wp-includes/post.php(3673): do_action('save_post', 167611, Object(WP_Post), false) #4 /home/amishyard/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(45): wp_insert_post(Array) #5 /home/amishyard/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(21): ActionScheduler_wpPostStore->save_post_array(Array) #6 /home/amishyard/public_html/wp-content/plugins/woocomme in /home/amishyard/public_html/wp-content/plugins/woo-custom-emails/admin/class-wcemails-admin.php on line 573`

**Comment by bluehiveinteractive** [comment]
WooCommerce version 3.5.2 and WordPress 4.9.8
